name: ner
supertask: token-classification
metrics:
  micro_f1:
    huggingface_id: seqeval
    long_name: Micro-average F1-score
  micro_f1_no_misc:
    huggingface_id: seqeval
    long_name: Micro-average F1-score without MISC tags
labels:
  O: []
  B-LOC:
    - B-LOCATION
    - B-PLACE
    - B-GPELOC
    - B-GPE_LOC
    - B-GPE/LOC
    - B-LOCGPE
    - B-LOC_GPE
    - B-LOC/GPE
    - B-LOCORG
    - B-LOC_ORG
    - B-LOC/ORG
    - B-ORGLOC
    - B-ORG_LOC
    - B-ORG/LOC
    - B-LOCPRS
    - B-LOC_PRS
    - B-LOC/PRS
    - B-PRSLOC
    - B-PRS_LOC
    - B-PRS/LOC
  I-LOC:
    - I-LOCATION
    - I-PLACE
    - I-GPELOC
    - I-GPE_LOC
    - I-GPE/LOC
    - I-LOCGPE
    - I-LOC_GPE
    - I-LOC/GPE
    - I-LOCORG
    - I-LOC_ORG
    - I-LOC/ORG
    - I-ORGLOC
    - I-ORG_LOC
    - I-ORG/LOC
    - I-LOCPRS
    - I-LOC_PRS
    - I-LOC/PRS
    - I-PRSLOC
    - I-PRS_LOC
    - I-PRS/LOC
  B-ORG:
    - B-ORGANIZATION
    - B-ORGANISATION
    - B-INST
    - B-GPEORG
    - B-GPE_ORG
    - B-GPE/ORG
    - B-ORGGPE
    - B-ORG_GPE
    - B-ORG/GPE
    - B-ORGPRS
    - B-ORG_PRS
    - B-ORG/PRS
    - B-PRSORG
    - B-PRS_ORG
    - B-PRS/ORG
    - B-OBJORG
    - B-OBJ_ORG
    - B-OBJ/ORG
    - B-ORGOBJ
    - B-ORG_OBJ
    - B-ORG/OBJ
  I-ORG:
    - I-ORGANIZATION
    - I-ORGANISATION
    - I-INST
    - I-GPEORG
    - I-GPE_ORG
    - I-GPE/ORG
    - I-ORGGPE
    - I-ORG_GPE
    - I-ORG/GPE
    - I-ORGPRS
    - I-ORG_PRS
    - I-ORG/PRS
    - I-PRSORG
    - I-PRS_ORG
    - I-PRS/ORG
    - I-OBJORG
    - I-OBJ_ORG
    - I-OBJ/ORG
    - I-ORGOBJ
    - I-ORG_OBJ
    - I-ORG/OBJ
  B-PER:
    - B-PERSON
  I-PER:
    - I-PERSON
  B-MISC:
    - B-MISCELLANEOUS
  I-MISC:
    - I-MISCELLANEOUS
